nginx:
  image: lucaspozzi/magento2:version1
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./docker/logs/nginx:/var/log/nginx
    - ./docker/config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./docker/config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/config/nginx/includes:/etc/nginx/includes
    - ./docker/config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  container_name: magento_php
  build: ./docker/docker-images/php
  links:
    - "mysql:mysql"
  volumes:
    - .:/var/www/html
    - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./docker/config/mail/sendmail:/usr/local/bin/sendmail
    - ./docker/logs/mail:/home
mysql:
  image: percona:5.6.34
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  volumes:
    - ./docker/data/mysql:/var/lib/mysql
#    - /home/user/Department/IT/DB_Dump:/home